### ISSUE TITLE
release tracking: Rio v0.0.15

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#159]
- [ ] https://github.com/raphamorim/rio/issues/150
- [ ] https://github.com/raphamorim/rio/issues/60
- [ ] https://github.com/raphamorim/rio/issues/133
- [ ] https://github.com/raphamorim/rio/issues/108
- [ ] https://github.com/raphamorim/rio/issues/124

**Comment by avelino** [comment]
This could be milestone
https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones

**Comment by raphamorim** [comment]
It is already a milestone @avelino

**Comment by raphamorim** [comment]
I am testing this version of releasing tracking for 0.0.15 but has both created.
