### ISSUE TITLE
Font stablization

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/rio#338]
- [x] Glyphs being get cut in half

<img width="215" alt="Screenshot 2023-11-14 at 18 19 54" src="https://github.com/raphamorim/rio/assets/3630346/34f26943-0391-4c0f-a447-5082c6782d5e">

- [ ] Powerline Glyphs are to small (this isn't exactly a font issue though but should be able to configure through config)

<img width="391" alt="Screenshot 2023-11-14 at 18 23 14" src="https://github.com/raphamorim/rio/assets/3630346/f9c493c7-8a75-4f9d-bce0-d99d7032ac10">

- [ ] Issues from https://github.com/raphamorim/rio/issues/328

- [ ] Tab bar overlaps text https://github.com/raphamorim/rio/issues/167

- [ ] Enable font for character ranges https://github.com/raphamorim/rio/issues/124

- [ ] Color offset and color issues using Fira Code font https://github.com/raphamorim/rio/issues/154

**Comment by raphamorim** [comment]
Closing this tracking issue in favor of the GH board.
